OBJECTS = main.o choi.o kim.o lee.o 
TARGET = prog
CC = gcc
CFLAGS = -Wall -W


$(TARGET) : $(OBJECTS)
	$(CC) $(CFLAGS) -o $@ $^

clean :
	rm $(TARGET)
	rm $(OBJECTS)

myfile : 
	cd ~
	ls -al *































